dgc:
  businessRulesDownload:
    endpoint: "https://dgca-businessrule-service-eu-test.cfapps.eu10.hana.ondemand.com"
  valueSetsDownload:
    endpoint: "https://dgca-businessrule-service-eu-test.cfapps.eu10.hana.ondemand.com"
  certificatesDownloader:
    endpoint: "https://dgca-verifier-service-eu-test.cfapps.eu10.hana.ondemand.com"




